name: Tinybird - CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  push_changes:
    uses: tinybirdco/ci/.github/workflows/cd.yml@main
    secrets: 
      admin_token: ${{ secrets.ADMIN_TOKEN }}
      tb_host: https://api.tinybird.co
